# STDIO Example
# ------------------------------------------------------------------------------
# A simple STDIN / STDOUT example. This script is used in the getting started
# guide:
#
# https://vector.dev/guides/getting-started

# Suricata evelogs
[sources.evelogs]
type = "redis"
data_type = "channel"
key = "suricata"
url = "redis://nprism_redis:6379"

# Parse evelogs
# See the Vector Remap Language reference for more info: https://vrl.dev
[transforms.evelog_parser]
type = "remap"
inputs = ["evelogs"]
source = '''
.message = parse_json!(.message)
'''

# Route evelogs by event_type
[transforms.evelog_route]
type = "route"
inputs = [ "evelog_parser" ]
route.flow = '.message.event_type == "flow"'
route.stats = '.message.event_type == "stats"'

[transforms.flow_parser]
type = "remap"
inputs = ["evelog_route.flow"]
source = '''

. = .message
.timestamp = to_unix_timestamp(parse_timestamp!(.timestamp, "%Y-%m-%dT%H:%M:%S%.6f%z"), "nanoseconds")

del(.message)
del(.source_type)

'''

# Clickhouse eveflow table
[sinks.clickhouse]
type = "clickhouse"
inputs = [ "flow_parser" ]
database = "suricata"
endpoint = "http://nprism_clickhouse:8123"
table = "eveflow"
auth.strategy = "basic"
auth.user = "clickhouse"
auth.password = "00000000"

# Print evelogs flow to stdout
#[sinks.print]
#type = "console"
#inputs = ["flow_parser"]
#encoding.codec = "json"

[api]
enabled = true
address = "0.0.0.0:8686"
