# STDIO Example
# ------------------------------------------------------------------------------
# A simple STDIN / STDOUT example. This script is used in the getting started
# guide:
#
# https://vector.dev/guides/getting-started

# Suricata evelog applayer
[sources.suricata_eveapplayer]
type = "redis"
data_type = "channel"
key = "suricata.applayer"
url = "redis://redis:6379"

# Parse evelog applayer
# See the Vector Remap Language reference for more info: https://vrl.dev
[transforms.eveapplayer_parser]
type = "remap"
inputs = ["suricata_eveapplayer"]
source = '''

. = parse_json!(.message)

.timestamp = to_unix_timestamp(parse_timestamp!(.timestamp, "%Y-%m-%dT%H:%M:%S%.6f%z"), "nanoseconds")

del(.message)
del(.source_type)

'''

# Clickhouse eveapplayer table
[sinks.clickhouse_eveapplayer]
type = "clickhouse"
inputs = [ "eveapplayer_parser" ]
database = "suricata"
endpoint = "http://clickhouse:8123"
table = "eveapplayer"
auth.strategy = "basic"
auth.user = "clickhouse"
auth.password = "00000000"

# Print eveapplayer applayer to stdout
#[sinks.print]
#type = "console"
#inputs = ["eveapplayer"]
#encoding.codec = "json"

[api]
enabled = true
address = "0.0.0.0:8686"
